#pragma once
#define BLAZE_ENGINE_CORE

#include "BlazeEngine/Core/BlazeEngineCoreDefines.h"

#include "BlazeEngine/Core/Common/Algorithm.h"
#include "BlazeEngine/Core/Common/Align.h"
#include "BlazeEngine/Core/Common/Buffer.h"
#include "BlazeEngine/Core/Common/BufferStream.h"
#include "BlazeEngine/Core/Common/Color.h"

#include "BlazeEngine/Core/Common/EventQueue.h"
#include "BlazeEngine/Core/Common/Format.h"
#include "BlazeEngine/Core/Common/Handle.h"
#include "BlazeEngine/Core/Common/HandleImpl.h"
#include "BlazeEngine/Core/Common/Hash.h"
#include "BlazeEngine/Core/Common/Range.h"
#include "BlazeEngine/Core/Common/Rect.h"
#include "BlazeEngine/Core/Common/Stream.h"
#include "BlazeEngine/Core/Common/SubStream.h"
#include "BlazeEngine/Core/Common/Tuple.h"
#include "BlazeEngine/Core/Common/View.h"

#include "BlazeEngine/Core/Container/Array.h"
#include "BlazeEngine/Core/Container/ArrayImpl.h"
#include "BlazeEngine/Core/Container/ArrayIterator.h"
#include "BlazeEngine/Core/Container/ArrayIteratorImpl.h"
#include "BlazeEngine/Core/Container/ArrayView.h"
#include "BlazeEngine/Core/Container/ArrayViewImpl.h"
#include "BlazeEngine/Core/Container/DualList.h"
#include "BlazeEngine/Core/Container/DualListImpl.h"
#include "BlazeEngine/Core/Container/HybridArray.h"
#include "BlazeEngine/Core/Container/List.h"
#include "BlazeEngine/Core/Container/ListImpl.h"
#include "BlazeEngine/Core/Container/Map.h"
#include "BlazeEngine/Core/Container/MapImpl.h"
#include "BlazeEngine/Core/Container/RawArray.h"
#include "BlazeEngine/Core/Container/RawArrayImpl.h"
#include "BlazeEngine/Core/Container/Set.h"
#include "BlazeEngine/Core/Container/SetImpl.h"
#include "BlazeEngine/Core/Container/UnorderedArray.h"
#include "BlazeEngine/Core/Container/UnorderedArrayImpl.h"
#include "BlazeEngine/Core/Container/VirtualList.h"
#include "BlazeEngine/Core/Container/VirtualListImpl.h"
#include "BlazeEngine/Core/Container/VirtualMap.h"
#include "BlazeEngine/Core/Container/VirtualMapImpl.h"

#include "BlazeEngine/Core/Console/Console.h"

#include "BlazeEngine/Core/Debug/Breakpoint.h"
#include "BlazeEngine/Core/Debug/Callstack.h"
#include "BlazeEngine/Core/Debug/Log.h"
#include "BlazeEngine/Core/Debug/Logger.h"
#include "BlazeEngine/Core/Debug/LoggerListener.h"
#include "BlazeEngine/Core/Debug/Result.h"

#include "BlazeEngine/Core/Event/EventDispatcher.h"
#include "BlazeEngine/Core/Event/EventDispatcherImpl.h"
#include "BlazeEngine/Core/Event/EventHandler.h"
#include "BlazeEngine/Core/Event/EventHandlerData.h"
#include "BlazeEngine/Core/Event/EventHandlerDataImpl.h"
#include "BlazeEngine/Core/Event/LambdaEventHandler.h"
#include "BlazeEngine/Core/Event/QueueEventDispatcher.h"

#include "BlazeEngine/Core/File/File.h"
#include "BlazeEngine/Core/File/FileStream.h"
#include "BlazeEngine/Core/File/FileSystem.h"
#include "BlazeEngine/Core/File/Path.h"

#include "BlazeEngine/Core/Math/Math.h"
#include "BlazeEngine/Core/Math/Matrix.h"
#include "BlazeEngine/Core/Math/Quaternion.h"
#include "BlazeEngine/Core/Math/Random.h"
#include "BlazeEngine/Core/Math/Shapes.h"
#include "BlazeEngine/Core/Math/Vector.h"

#include "BlazeEngine/Core/Memory/Allocator.h"
#include "BlazeEngine/Core/Memory/MallocAllocator.h"
#include "BlazeEngine/Core/Memory/MemoryListener.h"
#include "BlazeEngine/Core/Memory/MemoryManager.h"

#include "BlazeEngine/Core/Resource/DefaultResourceStorage.h"
#include "BlazeEngine/Core/Resource/Resource.h"
#include "BlazeEngine/Core/Resource/ResourceManager.h"
#include "BlazeEngine/Core/Resource/ResourceRef.h"
#include "BlazeEngine/Core/Resource/ResourceStorage.h"

#include "BlazeEngine/Core/String/FixedString.h"
#include "BlazeEngine/Core/String/String.h"
#include "BlazeEngine/Core/String/StringCommon.h"
#include "BlazeEngine/Core/String/StringIterator.h"
#include "BlazeEngine/Core/String/StringTypeConverter.h"
#include "BlazeEngine/Core/String/StringView.h"
#include "BlazeEngine/Core/String/UnicodeChar.h"

#include "BlazeEngine/Core/Threading/Thread.h"
#include "BlazeEngine/Core/Threading/ThreadGroup.h"
#include "BlazeEngine/Core/Threading/ThreadPool.h"

#include "BlazeEngine/Core/Time/Stopwatch.h"
#include "BlazeEngine/Core/Time/TimeInterval.h"
#include "BlazeEngine/Core/Time/TimePoint.h"
#include "BlazeEngine/Core/Time/Timing.h"

#include "BlazeEngine/Core/Type/FunctionTraits.h"
#include "BlazeEngine/Core/Type/IntegerTraits.h"
#include "BlazeEngine/Core/Type/IteratorTraits.h"
#include "BlazeEngine/Core/Type/TypeGroup.h"
#include "BlazeEngine/Core/Type/TypeTraits.h"
#include "BlazeEngine/Core/Type/TypeTraitsImpl.h"
#include "BlazeEngine/Core/Type/Variant.h"