#include "pch.h"
#include "BlazeEngine/Internal/BlazeEngineContext.h"
#include "SDLConversions.h"

namespace Blaze
{
	StringView GetSDLEventName(uint32 type)
	{
		if (type == blazeEngineContext.mainThreadTaskEventIdentifier)
			return "MAIN_THREAD_TASK_EVENT";
		if (type == blazeEngineContext.clientThreadExitEventIdentifier)
			return "CLIENT_THREAD_EXIT_EVENT";

		switch (type)
		{
		case SDL_EVENT_QUIT: return "QUIT_EVENT";
		case SDL_EVENT_TERMINATING: return "TERMINATING_EVENT";
		case SDL_EVENT_LOW_MEMORY: return "LOW_MEMORY_EVENT";
		case SDL_EVENT_WILL_ENTER_BACKGROUND: return "WILL_ENTER_BACKGROUND_EVENT";
		case SDL_EVENT_DID_ENTER_BACKGROUND: return "DID_ENTER_BACKGROUND_EVENT";
		case SDL_EVENT_WILL_ENTER_FOREGROUND: return "WILL_ENTER_FOREGROUND_EVENT";
		case SDL_EVENT_DID_ENTER_FOREGROUND: return "DID_ENTER_FOREGROUND_EVENT";
		case SDL_EVENT_LOCALE_CHANGED: return "LOCALE_CHANGED_EVENT";
		case SDL_EVENT_SYSTEM_THEME_CHANGED: return "SYSTEM_THEME_CHANGED_EVENT";
		case SDL_EVENT_DISPLAY_ORIENTATION: return "DISPLAY_ORIENTATION_EVENT";
		case SDL_EVENT_DISPLAY_ADDED: return "DISPLAY_ADDED_EVENT";
		case SDL_EVENT_DISPLAY_REMOVED: return "DISPLAY_REMOVED_EVENT";
		case SDL_EVENT_DISPLAY_MOVED: return "DISPLAY_MOVED_EVENT";
		case SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED: return "DISPLAY_DESKTOP_MODE_CHANGED_EVENT";
		case SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED: return "DISPLAY_CURRENT_MODE_CHANGED_EVENT";
		case SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED: return "DISPLAY_CONTENT_SCALE_CHANGED_EVENT";
		case SDL_EVENT_WINDOW_SHOWN: return "WINDOW_SHOWN_EVENT";
		case SDL_EVENT_WINDOW_HIDDEN: return "WINDOW_HIDDEN_EVENT";
		case SDL_EVENT_WINDOW_EXPOSED: return "WINDOW_EXPOSED_EVENT";
		case SDL_EVENT_WINDOW_MOVED: return "WINDOW_MOVED_EVENT";
		case SDL_EVENT_WINDOW_RESIZED: return "WINDOW_RESIZED_EVENT";
		case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED: return "WINDOW_PIXEL_SIZE_CHANGED_EVENT";
		case SDL_EVENT_WINDOW_METAL_VIEW_RESIZED: return "WINDOW_METAL_VIEW_RESIZED_EVENT";
		case SDL_EVENT_WINDOW_MINIMIZED: return "WINDOW_MINIMIZED_EVENT";
		case SDL_EVENT_WINDOW_MAXIMIZED: return "WINDOW_MAXIMIZED_EVENT";
		case SDL_EVENT_WINDOW_RESTORED: return "WINDOW_RESTORED_EVENT";
		case SDL_EVENT_WINDOW_MOUSE_ENTER: return "WINDOW_MOUSE_ENTER_EVENT";
		case SDL_EVENT_WINDOW_MOUSE_LEAVE: return "WINDOW_MOUSE_LEAVE_EVENT";
		case SDL_EVENT_WINDOW_FOCUS_GAINED: return "WINDOW_FOCUS_GAINED_EVENT";
		case SDL_EVENT_WINDOW_FOCUS_LOST: return "WINDOW_FOCUS_LOST_EVENT";
		case SDL_EVENT_WINDOW_CLOSE_REQUESTED: return "WINDOW_CLOSE_REQUESTED_EVENT";
		case SDL_EVENT_WINDOW_HIT_TEST: return "WINDOW_HIT_TEST_EVENT";
		case SDL_EVENT_WINDOW_ICCPROF_CHANGED: return "WINDOW_ICCPROF_CHANGED_EVENT";
		case SDL_EVENT_WINDOW_DISPLAY_CHANGED: return "WINDOW_DISPLAY_CHANGED_EVENT";
		case SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED: return "WINDOW_DISPLAY_SCALE_CHANGED_EVENT";
		case SDL_EVENT_WINDOW_SAFE_AREA_CHANGED: return "WINDOW_SAFE_AREA_CHANGED_EVENT";
		case SDL_EVENT_WINDOW_OCCLUDED: return "WINDOW_OCCLUDED_EVENT";
		case SDL_EVENT_WINDOW_ENTER_FULLSCREEN: return "WINDOW_ENTER_FULLSCREEN_EVENT";
		case SDL_EVENT_WINDOW_LEAVE_FULLSCREEN: return "WINDOW_LEAVE_FULLSCREEN_EVENT";
		case SDL_EVENT_WINDOW_DESTROYED: return "WINDOW_DESTROYED_EVENT";
		case SDL_EVENT_WINDOW_HDR_STATE_CHANGED: return "WINDOW_HDR_STATE_CHANGED_EVENT";
		case SDL_EVENT_KEY_DOWN: return "KEY_DOWN_EVENT";
		case SDL_EVENT_KEY_UP: return "KEY_UP_EVENT";
		case SDL_EVENT_TEXT_EDITING: return "TEXT_EDITING_EVENT";
		case SDL_EVENT_TEXT_INPUT: return "TEXT_INPUT_EVENT";
		case SDL_EVENT_KEYMAP_CHANGED: return "KEYMAP_CHANGED_EVENT";
		case SDL_EVENT_KEYBOARD_ADDED: return "KEYBOARD_ADDED_EVENT";
		case SDL_EVENT_KEYBOARD_REMOVED: return "KEYBOARD_REMOVED_EVENT";
		case SDL_EVENT_TEXT_EDITING_CANDIDATES: return "TEXT_EDITING_CANDIDATES_EVENT";
		case SDL_EVENT_MOUSE_MOTION: return "MOUSE_MOTION_EVENT";
		case SDL_EVENT_MOUSE_BUTTON_DOWN: return "MOUSE_BUTTON_DOWN_EVENT";
		case SDL_EVENT_MOUSE_BUTTON_UP: return "MOUSE_BUTTON_UP_EVENT";
		case SDL_EVENT_MOUSE_WHEEL: return "MOUSE_WHEEL_EVENT";
		case SDL_EVENT_MOUSE_ADDED: return "MOUSE_ADDED_EVENT";
		case SDL_EVENT_MOUSE_REMOVED: return "MOUSE_REMOVED_EVENT";
		case SDL_EVENT_JOYSTICK_AXIS_MOTION: return "JOYSTICK_AXIS_MOTION_EVENT";
		case SDL_EVENT_JOYSTICK_BALL_MOTION: return "JOYSTICK_BALL_MOTION_EVENT";
		case SDL_EVENT_JOYSTICK_HAT_MOTION: return "JOYSTICK_HAT_MOTION_EVENT";
		case SDL_EVENT_JOYSTICK_BUTTON_DOWN: return "JOYSTICK_BUTTON_DOWN_EVENT";
		case SDL_EVENT_JOYSTICK_BUTTON_UP: return "JOYSTICK_BUTTON_UP_EVENT";
		case SDL_EVENT_JOYSTICK_ADDED: return "JOYSTICK_ADDED_EVENT";
		case SDL_EVENT_JOYSTICK_REMOVED: return "JOYSTICK_REMOVED_EVENT";
		case SDL_EVENT_JOYSTICK_BATTERY_UPDATED: return "JOYSTICK_BATTERY_UPDATED_EVENT";
		case SDL_EVENT_JOYSTICK_UPDATE_COMPLETE: return "JOYSTICK_UPDATE_COMPLETE_EVENT";
		case SDL_EVENT_GAMEPAD_AXIS_MOTION: return "GAMEPAD_AXIS_MOTION_EVENT";
		case SDL_EVENT_GAMEPAD_BUTTON_DOWN: return "GAMEPAD_BUTTON_DOWN_EVENT";
		case SDL_EVENT_GAMEPAD_BUTTON_UP: return "GAMEPAD_BUTTON_UP_EVENT";
		case SDL_EVENT_GAMEPAD_ADDED: return "GAMEPAD_ADDED_EVENT";
		case SDL_EVENT_GAMEPAD_REMOVED: return "GAMEPAD_REMOVED_EVENT";
		case SDL_EVENT_GAMEPAD_REMAPPED: return "GAMEPAD_REMAPPED_EVENT";
		case SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN: return "GAMEPAD_TOUCHPAD_DOWN_EVENT";
		case SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION: return "GAMEPAD_TOUCHPAD_MOTION_EVENT";
		case SDL_EVENT_GAMEPAD_TOUCHPAD_UP: return "GAMEPAD_TOUCHPAD_UP_EVENT";
		case SDL_EVENT_GAMEPAD_SENSOR_UPDATE: return "GAMEPAD_SENSOR_UPDATE_EVENT";
		case SDL_EVENT_GAMEPAD_UPDATE_COMPLETE: return "GAMEPAD_UPDATE_COMPLETE_EVENT";
		case SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED: return "GAMEPAD_STEAM_HANDLE_UPDATED_EVENT";
		case SDL_EVENT_FINGER_DOWN: return "FINGER_DOWN_EVENT";
		case SDL_EVENT_FINGER_UP: return "FINGER_UP_EVENT";
		case SDL_EVENT_FINGER_MOTION: return "FINGER_MOTION_EVENT";
		case SDL_EVENT_FINGER_CANCELED: return "FINGER_CANCELED_EVENT";
		case SDL_EVENT_CLIPBOARD_UPDATE: return "CLIPBOARD_UPDATE_EVENT";
		case SDL_EVENT_DROP_FILE: return "DROP_FILE_EVENT";
		case SDL_EVENT_DROP_TEXT: return "DROP_TEXT_EVENT";
		case SDL_EVENT_DROP_BEGIN: return "DROP_BEGIN_EVENT";
		case SDL_EVENT_DROP_COMPLETE: return "DROP_COMPLETE_EVENT";
		case SDL_EVENT_DROP_POSITION: return "DROP_POSITION_EVENT";
		case SDL_EVENT_AUDIO_DEVICE_ADDED: return "AUDIO_DEVICE_ADDED_EVENT";
		case SDL_EVENT_AUDIO_DEVICE_REMOVED: return "AUDIO_DEVICE_REMOVED_EVENT";
		case SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED: return "AUDIO_DEVICE_FORMAT_CHANGED_EVENT";
		case SDL_EVENT_SENSOR_UPDATE: return "SENSOR_UPDATE_EVENT";
		case SDL_EVENT_PEN_PROXIMITY_IN: return "PEN_PROXIMITY_IN_EVENT";
		case SDL_EVENT_PEN_PROXIMITY_OUT: return "PEN_PROXIMITY_OUT_EVENT";
		case SDL_EVENT_PEN_DOWN: return "PEN_DOWN_EVENT";
		case SDL_EVENT_PEN_UP: return "PEN_UP_EVENT";
		case SDL_EVENT_PEN_BUTTON_DOWN: return "PEN_BUTTON_DOWN_EVENT";
		case SDL_EVENT_PEN_BUTTON_UP: return "PEN_BUTTON_UP_EVENT";
		case SDL_EVENT_PEN_MOTION: return "PEN_MOTION_EVENT";
		case SDL_EVENT_PEN_AXIS: return "PEN_AXIS_EVENT";
		case SDL_EVENT_CAMERA_DEVICE_ADDED: return "CAMERA_DEVICE_ADDED_EVENT";
		case SDL_EVENT_CAMERA_DEVICE_REMOVED: return "CAMERA_DEVICE_REMOVED_EVENT";
		case SDL_EVENT_CAMERA_DEVICE_APPROVED: return "CAMERA_DEVICE_APPROVED_EVENT";
		case SDL_EVENT_CAMERA_DEVICE_DENIED: return "CAMERA_DEVICE_DENIED_EVENT";
		case SDL_EVENT_RENDER_TARGETS_RESET: return "RENDER_TARGETS_RESET_EVENT";
		case SDL_EVENT_RENDER_DEVICE_RESET: return "RENDER_DEVICE_RESET_EVENT";
		case SDL_EVENT_RENDER_DEVICE_LOST: return "RENDER_DEVICE_LOST_EVENT";
		default: return "UNRECOGNIZED EVENT";
		}
	}
}